### ISSUE TITLE
LED Specs

### ISSUE THREAD

**Issue by iCityWork** [FujiNetWIFI/fujinet-hardware#11]
Hi Mozz,
I am going to make a batch of these for people, curious about the LED specs as nothing is given other than them being on the 3V3 rail.  Any specifics for the ratings? I see the DipTrace PCB file still links to the SMD LCDs for the Atari FujiNet.
Thank you as always for your amazing work!
Gavin

**Comment by mozzwald** [comment]
Nothing specific, any generic led should work. I bought this kit and they work fine:

https://www.amazon.com/gp/product/B07N2H23DC
