### ISSUE TITLE
Problem with CoCo .stl files

### ISSUE THREAD

**Issue by brucem5755** [FujiNetWIFI/fujinet-hardware#29]
I am unable to get the .stl files for the case to load into Creality Print or Creality Slicer 4.8.2.

Has anyone been able to successfully print from the .stls in the project file for the CoCo ?

**Comment by mozzwald** [comment]
I loaded the files into FlashPrint slicer for my Creator Pro 2 with no issues. 

Does it give you any sort of error message?

**Comment by brucem5755** [comment]
All I get is a message that says can’t open file.    I did try re-downloading and that made no difference.  

Other .stl files open fine.

**Comment by retrobrian** [comment]
I had a similar issue when I right-clicked from the file list and tried to use "save as". That method won't save the correct format.

Have you tried opening a specific STL and then click "Download Raw File"?
![Screenshot 2024-11-16 125435](https://github.com/user-attachments/assets/7a405f90-237c-4c87-b51c-729e56a4b02a)

**Comment by brucem5755** [comment]
Thanks for the tip.    When i downloaded as the "raw" file it worked fine.   

Thank you very much!!

**Comment by retrobrian** [comment]
Excellent! Thanks for letting us know!

Mozzwald, this one can be closed.
