### ISSUE TITLE
DB-19 Pins 19pcs: Aliexpress too short

### ISSUE THREAD

**Issue by iCityWork** [FujiNetWIFI/fujinet-hardware#30]
Ok, it's been a few years but I am back and trying to build some of the Apple II FujiNet's and I have a bit of a problem with the DB-19M to IDC20F adapter board.  The pins that are listed are too short for the hood for me, and the pins that we use in the Atari FN are too thick to fit into the holes on the PCB but they are long enough.  Is there another pin I should be using, or a hood that isn't as deep?
What am I missing? 
Thanks guys.

![IMG_6867](https://github.com/user-attachments/assets/a85c72dd-6b97-4745-a7cd-4b97176ab773)

**Comment by mozzwald** [comment]
First, which Apple II FujiNet device are you building? There's several options in here and you should use the correct DB19 adapter for the correct FujiApple device.

It looks like you are building this https://github.com/FujiNetWIFI/fujinet-hardware/tree/master/AppleII/DB-19M-Adapter-Male-Rev1 which if is correct, you have the wrong IDC20 connector on it. If you view the README there, it shows you how to solder the pins correctly.

The other DB19 Female adapter for the SMD FujiApple is at https://github.com/FujiNetWIFI/fujinet-hardware/tree/master/AppleII/DB-19M-Adapter-Female-Rev1.1 and has a text description of how to install the pins
