### ISSUE TITLE
SIO Receptacle pins are short preventing some cables from remaining seated

### ISSUE THREAD

**Issue by mozzwald** [FujiNetWIFI/fujinet-hardware#7]
Some users have reported that their SIO cables pop out or fall out of the FujiNet receptacle. The pins used on FujiNet are shorter than an original SIO receptacle. To combat this issue I am testing some different pins that are longer. Preliminary testing looks promising.
<img src="https://user-images.githubusercontent.com/1191098/111054963-8c302d00-8436-11eb-9d30-68b641727fbb.jpg" width="300" />
<img src="https://user-images.githubusercontent.com/1191098/111055028-42941200-8437-11eb-9e69-3b3701f2b15c.jpg" width="300" />
<img src="https://user-images.githubusercontent.com/1191098/111055032-5e97b380-8437-11eb-9ef6-8f122e10ff6e.jpg" width="300" />

**Comment by iCityWork** [comment]
Do you have the 3D STL for the little pin jig you made to aid in soldering these new pins in the correct place?
Thanks,
Gavin

**Comment by mozzwald** [comment]
> Do you have the 3D STL for the little pin jig you made to aid in soldering these new pins in the correct place? Thanks, Gavin

I do and will post them this weekend, thx for the reminder ;)

Closing, issue fixed with d48371e

**Comment by iCityWork** [comment]
call me crazy but I am not seeing the STL for it yet. What am I missing?

**Comment by mozzwald** [comment]
> call me crazy but I am not seeing the STL for it yet. What am I missing?

I tagged you on AA with the file:

https://atariage.com/forums/topic/327694-fujinet-v16-hardware/?do=findComment&comment=4959920

When I have time, I will put them in this repo with some instructions

**Comment by iCityWork** [comment]
Oh thank you sir, I don't go to AA that often.  Much appreciated.
